name: claude

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:

  initialize:
    uses: ./.github/workflows/core--initializer.yaml

  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '/claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '/claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '/claude') || contains(github.event.issue.title, '/claude')))
    needs: [initialize]
    permissions:
      contents: read
      id-token: write
      issues: read
      pull-requests: read
    uses: emcd/python-project-common/.github/workflows/xrepo--claude.yaml@v1.20
    with:
      allowed-tools: 'Bash(git add:*),Bash(git branch:*),Bash(git checkout:*),Bash(git diff:*),Bash(git log:*),Bash(git ls-files:*),Bash(git remote:*),Bash(git reset:*),Bash(git rev-parse:*),Bash(git rm:*),Bash(git status),Bash(hatch:*),Bash(pip:*),Bash(python:*),Edit,Write'
      python-version: '${{ fromJSON(needs.initialize.outputs.python-versions)[0] }}'
      timeout-minutes: 20
    secrets:
      anthropic-api-key: '${{ secrets.ANTHROPIC_API_KEY }}'
